//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESolutions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESolutions.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is no valid boolean..
        /// </summary>
        internal static string InvalidFormatForBoolean {
            get {
                return ResourceManager.GetString("InvalidFormatForBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The provided string is no valid date-time.&quot;.
        /// </summary>
        internal static string InvalidFormatForDateTime {
            get {
                return ResourceManager.GetString("InvalidFormatForDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is no valid Decimal..
        /// </summary>
        internal static string InvalidFormatForDecimal {
            get {
                return ResourceManager.GetString("InvalidFormatForDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is no valid double..
        /// </summary>
        internal static string InvalidFormatForDouble {
            get {
                return ResourceManager.GetString("InvalidFormatForDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is no valid guid..
        /// </summary>
        internal static string InvalidFormatForGuid {
            get {
                return ResourceManager.GetString("InvalidFormatForGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string is no valid integer..
        /// </summary>
        internal static string InvalidFormatForInt32 {
            get {
                return ResourceManager.GetString("InvalidFormatForInt32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided string contains no digits..
        /// </summary>
        internal static string InvalidFormatNoDigits {
            get {
                return ResourceManager.GetString("InvalidFormatNoDigits", resourceCulture);
            }
        }
    }
}
